```{r}
rr <- read.csv('model_selection_results/ridge_reg_results.csv')
rc <- read.csv('model_selection_results/ridge_class_results.csv')
rfr <- read.csv('model_selection_results/rf_reg_results.csv')
rfc <- read.csv('model_selection_results/rf_class_results.csv')
svc <- read.csv('model_selection_results/linear_svc_results.csv')
mnnb <- read.csv('model_selection_results/multinomial_nb_results.csv')

head(rr)
names(rr)
```

```{r}
library (dplyr)

rr$model <- 'rr'
svc$model <- 'svc'
mnnb$model <- 'mnnb'
rfc$model <- 'rfc'
rfr$model <- 'rfr'
rc$model <- 'rc'

data <- bind_rows(rr, svc, mnnb, rfc, rfr, rc)

data <- data %>%
  rename(ngram = param_tfidf__ngram_range)


```

```{r}
library(ggplot2)

rr <- data %>%
  filter(model == 'rr')
rr_box <- ggplot(data=rr, aes(x=ngram, y=mean_test_score, fill=ngram)) +
  geom_boxplot(aes(alpha=0.3)) + 
  theme(legend.position='none')
rr_box
```

```{r}
library(dplyr)

rr <- rr %>%
  mutate(mean_test_score = -1 * mean_test_score)

rr_hist <- ggplot(data=rr, aes(x=mean_test_score)) + 
  geom_histogram(binwidth=0.1) + 
  facet_wrap(~ ngram) + 
  labs(
    title = 'Mean Squared Error by N-Gram Range',
    x = 'MSE',
    y = 'Count'
  )

rr_hist
```


```{r}
rr <- rr %>%
  filter(mean_test_score < 5)

ggplot(rr, aes(x = mean_test_score)) +
  geom_histogram()
  
ggplot(rr, aes(sample = mean_test_score)) +
  stat_qq() + 
  stat_qq_line(color = 'red') +
  theme_minimal()
  
```

```{r}
class_models <- c('mnnb', 'rc', 'rfc', 'svc')
reg_models <- c('rfr', 'rr')

class <- data %>%
  filter(model %in% class_models)
  
ggplot(data=class, aes(x = model, y = mean_test_score, fill=model)) + 
  geom_boxplot() + 
  labs(
    title = 'F1 Score by Model: Classification',
    x = 'Model',
    y = 'F1 Macro'
  ) + 
  scale_x_discrete(labels = c(
    'mnnb' = 'Multinomial Naive Bayes',
    'rc' = 'Ridge Classifier',
    'rfc' = 'Random Forest Classifier',
    'svc' = 'Linear SVC'
  )) + 
  theme(legend.position = 'none')
```
```{r}
summ <- class %>%
  group_by(model) %>%
  summarise(
    avg_score = mean(mean_test_score, na.rm = TRUE)
  )

summ

class_models <- c('rc', 'svc')

class <- class %>%
  filter(model %in% class_models) 

class$model <- factor(class$model,
                      levels = c('rc', 'svc'),
                      labels = c('Ridge Classifier', 'Linear SVC'))
  
# ggplot(class, aes(sample = mean_test_score)) + 
#   stat_qq() + 
#   stat_qq_line(color='red') + 
#   facet_wrap(~ model) + 
#   labs(
#     x = 'Theoretical Quantiles (Normal)',
#     y = 'Observed Quantiles',
#     title = 'Observed vs Theoretical Quantiles: Ridge Classifier and Linear SVC'
#   )

ggplot(class, aes(x = mean_test_score)) + 
  geom_histogram() + 
  facet_wrap(~ model) + 
  labs(
    x = 'F1 Score (Macro)',
    y = 'Count'
  )
```


```{r}
wilcox.test(mean_test_score ~ model, data = class)

boot <- replicate(10000,
    mean(sample(svc$mean_test_score, replace = TRUE)) - 
    mean(sample(rc$mean_test_score, replace = TRUE))
)

quantile(boot, c(0.025, 0.975))

ggplot(class, aes(x = model, y = mean_test_score, fill = model)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.5) + 
  labs(
    title = 'F1 Score by Model: Ridge Classifier vs Linear SVC',
    x = 'Model',
    y = 'F1 Score (Macro)'
  )

drop_cols <- c('mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'params', 
               'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 
               'split4_test_score', 'split0_test_score', 'std_test_score', 'model', 'rank_test_score')

library(tidyr)

num_df <- names(class <- filter(if_any(where(is.numeric))))
num_df

outliers <- class %>%
  filter(model == 'Linear SVC') %>%
  select(-all_of(drop_cols)) %>% 
  pivot_longer(
    cols = -mean_test_score,
    names_to = 'parameter',
    values_to = 'values'
  )

ggplot(outliers, aes(x = ))

```

```{r}
boot <- replicate(10000,
    mean(sample(svc$mean_test_score, replace = TRUE)) - 
    mean(sample(rr$mean_test_score, replace = TRUE))
)
# alpha 0.1
quantile(boot, c(0.05, 0.95))

# alpha 0.05
quantile(boot, c(0.025, 0.975))

# alpha 0.01
quantile(boot, c(0.005, 0.995))

# alpha 0.001
quantile(boot, c(0.0005, 0.9995))

vector <- boot
boot <- data.frame(boot)


ggplot(data=boot, aes(x=boot)) + 
  geom_histogram(aes(y=..density..), color='black', fill='lightblue', bins=200) + 
  xlim(-1, 1) + 
  geom_vline(xintercept = 0) + 
  # stat_function(fun = dnorm, args = list(mean = mean(vector), sd = sd(vector)), color = "red", size = 1) + 
  labs(
    title = 'F1-Score Difference Between Linear SVC and Ridge Regression',
    x = 'Difference in Mean (Linear SVC - Ridge)',
    y = 'Density'
  )

```

```{r}
n2 <- rr %>%
  filter(rr$ngram == '(1, 2)')

n3 <- rr %>%
  filter(rr$ngram == '(1, 3)')



boot <- replicate(100000,
    mean(sample(n2$mean_test_score, replace = TRUE)) - 
    mean(sample(n3$mean_test_score, replace = TRUE))
)

# alpha 0.1
quantile(boot, c(0.05, 0.95))

# alpha 0.05
quantile(boot, c(0.025, 0.975))

# alpha 0.01
quantile(boot, c(0.005, 0.995))
vector <- boot
boot <- data.frame(boot)

ggplot(data=boot, aes(x=boot)) + 
  geom_histogram(aes(y=..density..), color='black', fill='lightblue', bins=200) + 
  xlim(-0.5, 0.5) + 
  geom_vline(xintercept = 0) + 
  # stat_function(fun = dnorm, args = list(mean = mean(vector), sd = sd(vector)), color = "red", size = 1) + 
  labs(
    title = 'F1-Score Difference Bigram- and Trigram-Recognizing Ridge Regressors',
    x = 'Difference in Mean (Bigram - Trigram)',
    y = 'Density'
  )
```

```{r}
best <- rr %>%
  filter(rank_test_score == 1)

best$params
names(best)
best
```

```{r}


rr$ngram_range <- ifelse(rr$ngram == '(1, 2)', 0, 1)
rr

params <- c('ngram_range', 'param_tfidf__min_df', 'param_tfidf__max_df', 'param_clf__alpha')


param_subsets <- unlist(
  lapply(1:length(params), function(k) {
    combn(params, k, simplify=FALSE)
  }),
  recursive=FALSE
)

models <- list()

for (i in seq_along(param_subsets)) {
  vars <- param_subsets[[i]]
  formula <- as.formula(
    paste('mean_test_score ~ ', paste(vars, collapse=' + '))
  )
  models[[i]] <- lm(formula, data=rr)
}

coef_df <- data.frame()

for (i in seq_along(models)) {
  coefs <- coef(models[[i]])
  
  temp <- data.frame(
    term = names(coefs),
    estimate = coefs,
    model_id = i,
    num_params = length(param_subsets[[i]]),
    params = paste(param_subsets[[i]], collapse = ",")
  )
  
  coef_df <- rbind(coef_df, temp)
}

coef_df <- coef_df[coef_df$term != "(Intercept)", ]
coef_df
ggplot(coef_df, aes(x = num_params, y = estimate, color = term)) +
  geom_jitter(width = 0.1) +
  geom_smooth(se = FALSE) +
  labs(x = "Number of Parameters in Model",
       y = "Coefficient",
       title = "Coefficient Variation Across All Model Subsets")
```

```{r}
ggplot(data=rr, aes(x=param_tfidf__min_df, y=mean_test_score)) + 
  geom_point(data=rr, color='red') + 
  geom_smooth(method = "lm", se = TRUE)

ggplot(data=rr, aes(x=ngram_range, y=mean_test_score)) + 
  geom_point(data=rr, color='red') + 
  geom_smooth(method = "lm", se = TRUE)

ggplot(data=rr, aes(x=param_tfidf__max_df, y=mean_test_score)) + 
  geom_point(data=rr, color='red') + 
  geom_smooth(method = "lm", se = TRUE)

ggplot(data=rr, aes(x=param_tfidf__min_df, y=mean_test_score)) + 
  geom_point(data=rr, color='red') + 
  geom_smooth(method = "lm", se = TRUE)

ggplot(data=rr, aes(x=param_tfidf__min_df, y=param_tfidf__max_df, fill=mean_test_score)) + 
    geom_tile() +
    theme()

```



